TIMESTAMPS:
03:00 - Learn keyboard shortcuts
04:37 - Practice on 10fastfingers.com
06:12 - Practice on keybr.com
07:50 - Try to use only the keyboard
09:56 - Try to never look at the keyboard
10:43 - Fingers to correct resting position
11:16 - Try to make noise
12:12 - Treat it as a game